environment:
  DATABASE_URL: ${DATABASE_URL}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_SCHEMA: ${DATABASE_SCHEMA}
  JWT_KEY: ${JWT_KEY}
packages:
  - name: authentication
    actions:
      - name: authenticate
        runtime: go:1.20
