environment:
  DATABASE_URL: ""
  DATABASE_USER: ""
  DATABASE_PASSWORD: ""
  DATABASE_NAME: ""
  DATABASE_SCHEMA: ""
  JWT_KEY: lkjhaskljdajkdlsfjklsdgjklssdljkgff
packages:
- name: authentication
  actions:
  - name: authenticate
    runtime: go:1.20
