environment:
  DATABASE_URL: ""
  DATABASE_USER: ""
  DATABASE_PASSWORD: ""
  DATABASE_NAME: ""
  JWT_KEY: ""
packages:
  - name: authentication
    actions:
      - name: authenticate
        runtime: go:1.20
