name: Deploy DigitalOcean Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install doctl
        run: |
          sudo snap install doctl

      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN

      - name: Connect to DigitalOcean Functions Namespace
        run: |
          doctl serverless connect

      - name: Deploy Function to DigitalOcean
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_SCHEMA: ${{ secrets.DATABASE_SCHEMA }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        working-directory: ../../
        run: |
          doctl serverless deploy my-burger-auth --remote-build --env DATABASE_URL=$DATABASE_URL --env DATABASE_USER=$DATABASE_USER --env DATABASE_PASSWORD=$DATABASE_PASSWORD --env DATABASE_NAME=$DATABASE_NAME --env DATABASE_SCHEMA=$DATABASE_SCHEMA --env JWT_KEY=$JWT_KEY